result =
  File.stream!("file.txt")
  |> Enum.map(&String.trim/1)
  |> Enum.map(&String.split/1)
  |> Enum.map(fn inner_list -> Enum.map(inner_list, &String.to_integer/1) end)
  |> Enum.map(&List.to_tuple/1)
  |> Enum.unzip()
  |> Tuple.to_list()
  |> Enum.map(fn inner_list -> Enum.sort(inner_list) end)
  |> Enum.zip()
  |> Enum.map(&Tuple.to_list/1)
  |> Enum.map(fn inner_list -> Enum.reduce(inner_list, fn x, acc -> abs(acc - x) end) end)
  |> Enum.reduce(fn x, acc -> acc + x end)

IO.inspect(result)
